use college;

CREATE TABLE SALESMAN
(
SALESMAN_ID INT,
NAME VARCHAR(20),
CITY VARCHAR(20),
COMMISSION Decimal(4,2), --before decimal it can include 4 values and after decimal it can include 2 decimal 
primary key(SALESMAN_ID));

INSERT INTO SALESMAN VALUES(5001,'JAMES HOOG','NEW YORK',0.15);
INSERT INTO SALESMAN VALUES(5002,'NAIL KNITE','PARIS',0.13);
INSERT INTO SALESMAN VALUES(5005,'PIT ALEX','LONDON',0.11);
INSERT INTO SALESMAN VALUES(5006,'MC LYON','PARIS',0.14);
INSERT INTO SALESMAN VALUES(5007,'PAUL ADAM','ROME',0.13);
INSERT INTO SALESMAN VALUES(5003,'LAUSON HEN','SAN JOSE',0.12);select * from salesman;--truncate table salesman;--drop table SALESMAN;